#!/bin/sh

# set prefered launcher
PREFERED_LAUNCHER=dmenu
# set path where urls will be stored
URL_FILE_PATH=$HOME/.bmks/
# name of file urls will be stored in
URL_FILE_NAME=urls
# number of lines shown in the dmenu
DMENU_LINE_DISPLAY=8
# hidden prefix, links that i dont visit so often
HIDDEN_PREFIX=*

show_usage() {
    printf "bmks: unix bookmark management that sucks less

Usage: bmks [options...]
bmks help
	show this help message
bmks ls
	show all bookmarks
bmks hidden
	show hidden bookmarks, links that you don't visit so often
	prefixed with * by default.
	example: *google = google.com
	run with HIDDEN=1 enviroment variable
bmks dmenu
	manual switch for displaying bookmarks in dmenu
bmks clip
	copies the choosen url to the clipboard and paste it
	if a text area is available

To add bookmarks open ${URL_FILE_PATH}${URL_FILE_NAME} in a text
editor and add your bookmark in the format: title = URL
(for example google = https://google.com)

Lines that begins with # character are interpreted as comments.

Configuration is done by directly editing the script. dmenu is the
only supported launcher (add your favourite launcher if you want).
it will allow you to choose a bookmark and open it in your default
browser.

If you would prefer to have your bookmarks stored in alternate
location there are also variables that can be changed for that. The
default is ${URL_FILE_PATH}${URL_FILE_NAME}\n"
}

bmks_hidden() {
    bmks_check
    grep -vE "#|^$" $URL_FILE_PATH/$URL_FILE_NAME \
	| sort -u \
	| grep -E '^\'${HIDDEN_PREFIX}'' \
	| sed 's/^\'${HIDDEN_PREFIX}'//g'
}

bmks_ls() {
    bmks_check
    grep -vE '#|^$|^\'${HIDDEN_PREFIX}'' $URL_FILE_PATH/$URL_FILE_NAME | sort -u
}

bmks_display() {
    # bmks_check
    case $PREFERED_LAUNCHER in
	dmenu) ([[ $HIDDEN -eq 1 ]] && bmks_hidden || bmks_ls) \
		   | dmenu -l ${DMENU_LINE_DISPLAY} \
		   | awk '{print $(NF)}' \
		   | xargs -I '{}' $BROWSER {} ;;
	# in case if you want to add another launchers
    esac
}

bmks_clip() {
    bmks_ls \
	| dmenu -l ${DMENU_LINE_DISPLAY} \
	| awk '{print $(NF)}' \
	| xclip -sel clip \
	&& xclip -o -sel clip
}

bmks_check() {
    [ ! -s $URL_FILE_PATH/$URL_FILE_NAME ]  \
	&& printf "Error: No bookmarks found to display. Try adding some!\n\n" \
	&& show_usage \
	&& exit 0
}

[ ! -d $URL_FILE_PATH ] && mkdir $URL_FILE_PATH
[ ! -f $URL_FILE_PATH/$URL_FILE_NAME ] && touch $URL_FILE_PATH/$URL_FILE_NAME

case "$1" in
    "help") show_usage ;;
    "ls") bmks_ls ;;
    "dmenu") PREFERED_LAUNCHER=$1; bmks_display ;;
    "clip") bmks_clip ;;
    # Filter for links that i dont visit often
    "hidden") bmks_hidden ;;
    *) bmks_display ;;
esac
